<?php
$member    = $this->memberService->getById($_SESSION['member_id']);
$nameFirst = $member->getNameFirst( );
$nameLast  = $member->getNameLast( );
?>
<article>
    <section>
        <h1>Welcome, <?php echo $nameLast . " " . $nameFirst ?>!</h1>
    </section>
    <section>
        <h2>List of article categories:</h2>
        <ul>
            <?php foreach($this->categories as $category): ?>
                <li><a href='<?php echo $this->url('control-panel', array('controller' => 'index', 'action' => 'category', 'id' => $category->getId( )));?>'><?php echo $category->getTitle( ); ?></a></li>
            <?php endforeach; ?>
        <ul>
    </section>
</article>